version: '3.8'

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_TCP_PORT=3307
    ports:
      - "3307:3307"
    volumes:
      - db:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_VENDOR=mysql
      - DB_ADDR=mysqldb
      - DB_PORT=3307
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - KEYCLOAK_ADMIN=root
      - KEYCLOAK_ADMIN_PASSWORD=root
    ports:
      - "8081:8081"
    command: ["start-dev", "--http-port=8081"]
    depends_on:
      - mysqldb
    volumes:
      - keycloak_data:/opt/keycloak/data

  parco-spring:
    build: .
    depends_on:
      - keycloak
      - mysqldb

    restart: on-failure
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3307/$MYSQLDB_DATABASE?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.security.oauth2.resourceserver.jwt.issuer-uri" : "http://localhost:8081/realms/Parco",
        "spring.security.oauth2.resourceserver.jwt.jwk-set-uri" : "http://keycloak:8081/realms/Parco/protocol/openid-connect/certs"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  angular-app:
    image: radumocanu02/parco-angular:0.0.4
    ports:
      - "4200:4200"
    depends_on:
      - keycloak
      - parco-spring
    environment:
      - NODE_ENV=production

volumes:
  db:
  keycloak_data:
