services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command:
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=root
      - KEYCLOAK_ADMIN_PASSWORD=root
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak_data:/opt/jboss/keycloak/standalone/data
